# Generated by Django 4.2 on 2023-04-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=4)),
                ('popularity', models.IntegerField()),
                ('longtitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('plane_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('seats', models.IntegerField()),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('hub_id', models.AutoField(primary_key=True, serialize=False)),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.airline')),
                ('airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.airline')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='main.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='main.airport')),
                ('plane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plane')),
            ],
        ),
    ]
