# Generated by Django 4.2 on 2023-04-09 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='range',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hub',
            name='airport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.airport', verbose_name='airport'),
        ),
    ]
