# Generated by Django 4.2 on 2023-04-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_plane_range_alter_hub_airport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='registration',
            field=models.CharField(default='SP-LSD', max_length=6),
            preserve_default=False,
        ),
    ]
