# Generated by Django 4.2 on 2023-04-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_plane_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='plane_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.plane'),
        ),
    ]
