# Generated by Django 4.2 on 2023-04-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_flight_plane_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline_id',
        ),
    ]
