# Generated by Django 4.2 on 2023-04-10 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_flight_airline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='main.airport', verbose_name='Arrival airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='main.airport', verbose_name='Departure airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='plane_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.plane', verbose_name='Aircraft'),
        ),
    ]
