# Generated by Django 4.2 on 2023-04-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='registration',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
