# Generated by Django 4.2 on 2023-04-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_plane_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='registration',
            field=models.CharField(max_length=6),
        ),
    ]
