# Generated by Django 4.2 on 2023-04-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_plane_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(null=True),
        ),
    ]
