# Generated by Django 4.2 on 2023-04-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_flight_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longtitude',
            field=models.IntegerField(default=0),
        ),
    ]
