# Generated by Django 4.2 on 2023-04-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Airline name'),
        ),
    ]
