# Generated by Django 4.2 on 2023-04-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_airline_carried_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='completed_flights',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
