# Generated by Django 4.2 on 2023-04-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_airline_completed_flights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='budget',
            field=models.IntegerField(default=3000000),
        ),
        migrations.AlterField(
            model_name='airline',
            name='carried_passengers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airline',
            name='completed_flights',
            field=models.IntegerField(default=0),
        ),
    ]
